# coding: utf-8

"""
    Orbital State Management API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spacetower_orbital_state_management.models.harris_priester_atmosphere import HarrisPriesterAtmosphere

class TestHarrisPriesterAtmosphere(unittest.TestCase):
    """HarrisPriesterAtmosphere unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HarrisPriesterAtmosphere:
        """Test HarrisPriesterAtmosphere
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HarrisPriesterAtmosphere`
        """
        model = HarrisPriesterAtmosphere()
        if include_optional:
            return HarrisPriesterAtmosphere(
                solar_flux = 65
            )
        else:
            return HarrisPriesterAtmosphere(
                solar_flux = 65,
        )
        """

    def testHarrisPriesterAtmosphere(self):
        """Test HarrisPriesterAtmosphere"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
