# coding: utf-8

"""
    Orbital State Management API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spacetower_orbital_state_management.models.variable_step_integrator_configuration import VariableStepIntegratorConfiguration

class TestVariableStepIntegratorConfiguration(unittest.TestCase):
    """VariableStepIntegratorConfiguration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VariableStepIntegratorConfiguration:
        """Test VariableStepIntegratorConfiguration
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VariableStepIntegratorConfiguration`
        """
        model = VariableStepIntegratorConfiguration()
        if include_optional:
            return VariableStepIntegratorConfiguration(
                step_min = 1.337,
                step_max = 1.337,
                position_error = 1.337,
                variable_step_integrator_type = 'DORMAND_PRINCE_54'
            )
        else:
            return VariableStepIntegratorConfiguration(
        )
        """

    def testVariableStepIntegratorConfiguration(self):
        """Test VariableStepIntegratorConfiguration"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
