# coding: utf-8

"""
    Orbital State Management API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spacetower_orbital_state_management.models.earth_oriented_maneuver_attitude_law import EarthOrientedManeuverAttitudeLaw

class TestEarthOrientedManeuverAttitudeLaw(unittest.TestCase):
    """EarthOrientedManeuverAttitudeLaw unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EarthOrientedManeuverAttitudeLaw:
        """Test EarthOrientedManeuverAttitudeLaw
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EarthOrientedManeuverAttitudeLaw`
        """
        model = EarthOrientedManeuverAttitudeLaw()
        if include_optional:
            return EarthOrientedManeuverAttitudeLaw(
                earth_oriented_axis_in_space_object_frame = spacetower_orbital_state_management.models.vector3_d.Vector3D(
                    x = 1.337, 
                    y = 1.337, 
                    z = 1.337, ),
                maneuver_direction_type = 'PROGRADE'
            )
        else:
            return EarthOrientedManeuverAttitudeLaw(
                earth_oriented_axis_in_space_object_frame = spacetower_orbital_state_management.models.vector3_d.Vector3D(
                    x = 1.337, 
                    y = 1.337, 
                    z = 1.337, ),
                maneuver_direction_type = 'PROGRADE',
        )
        """

    def testEarthOrientedManeuverAttitudeLaw(self):
        """Test EarthOrientedManeuverAttitudeLaw"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
