# coding: utf-8

"""
    Orbital State Management API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spacetower_orbital_state_management.models.fixed_step_integrator_configuration import FixedStepIntegratorConfiguration

class TestFixedStepIntegratorConfiguration(unittest.TestCase):
    """FixedStepIntegratorConfiguration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FixedStepIntegratorConfiguration:
        """Test FixedStepIntegratorConfiguration
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FixedStepIntegratorConfiguration`
        """
        model = FixedStepIntegratorConfiguration()
        if include_optional:
            return FixedStepIntegratorConfiguration(
                step = 1.337,
                fixed_step_integrator_type = 'RUNGE_KUTTA_4'
            )
        else:
            return FixedStepIntegratorConfiguration(
                step = 1.337,
        )
        """

    def testFixedStepIntegratorConfiguration(self):
        """Test FixedStepIntegratorConfiguration"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
