# coding: utf-8

"""
    Orbital State Management API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spacetower_orbital_state_management.models.vector3_d import Vector3D

class TestVector3D(unittest.TestCase):
    """Vector3D unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Vector3D:
        """Test Vector3D
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Vector3D`
        """
        model = Vector3D()
        if include_optional:
            return Vector3D(
                x = 1.337,
                y = 1.337,
                z = 1.337
            )
        else:
            return Vector3D(
                x = 1.337,
                y = 1.337,
                z = 1.337,
        )
        """

    def testVector3D(self):
        """Test Vector3D"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
