# coding: utf-8

"""
    Orbital State Management API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spacetower_orbital_state_management.models.radiation_coefficients import RadiationCoefficients

class TestRadiationCoefficients(unittest.TestCase):
    """RadiationCoefficients unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RadiationCoefficients:
        """Test RadiationCoefficients
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RadiationCoefficients`
        """
        model = RadiationCoefficients()
        if include_optional:
            return RadiationCoefficients(
                radiation_coefficients_type = 'REFLECTION_ABSORPTION'
            )
        else:
            return RadiationCoefficients(
                radiation_coefficients_type = 'REFLECTION_ABSORPTION',
        )
        """

    def testRadiationCoefficients(self):
        """Test RadiationCoefficients"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
