from simple_pytorch_wrapper.examples.CNN_example_run import CNN_example_run
from simple_pytorch_wrapper.examples.FNN_example_run import FNN_example_run
from simple_pytorch_wrapper.examples.load_example_dataset import load_language_digit_example_dataset