__built_time__        =  "built at Mon Jan  6 12:21:42 2025_CST"
__name__              =  "pyasd"
__version__           =  "0.1.4"
__author__            =  "Shunhong Zhang"
__author_email__      =  "zhangshunhong.pku@gmail.com"
__url__               =  "https://pypi.org/project/pyasd/"
__license__           =  "MIT LICENSE"
__platform__          =  "linux"
