# coding: utf-8

"""
    Measurements Generation API

    Measurements Generation API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spacetower_measurement_generation_python_client.models.ground_station import GroundStation

class TestGroundStation(unittest.TestCase):
    """GroundStation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GroundStation:
        """Test GroundStation
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GroundStation`
        """
        model = GroundStation()
        if include_optional:
            return GroundStation(
                name = '',
                latitude = 1.337,
                longitude = 1.337,
                altitude = 1.337,
                minimum_elevation = 1.337,
                station_mask = spacetower_measurement_generation_python_client.models.station_mask.StationMask(
                    station_mask = [
                        1.337
                        ], )
            )
        else:
            return GroundStation(
                latitude = 1.337,
                longitude = 1.337,
                altitude = 1.337,
        )
        """

    def testGroundStation(self):
        """Test GroundStation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
