# coding: utf-8

"""
    Measurements Generation API

    Measurements Generation API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spacetower_measurement_generation_python_client.models.ra_dec_measurements_request import RaDecMeasurementsRequest

class TestRaDecMeasurementsRequest(unittest.TestCase):
    """RaDecMeasurementsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RaDecMeasurementsRequest:
        """Test RaDecMeasurementsRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RaDecMeasurementsRequest`
        """
        model = RaDecMeasurementsRequest()
        if include_optional:
            return RaDecMeasurementsRequest(
                right_ascension_standard_deviation = 1.337,
                declination_standard_deviation = 1.337,
                ground_station = spacetower_measurement_generation_python_client.models.ground_station.GroundStation(
                    name = '', 
                    latitude = 1.337, 
                    longitude = 1.337, 
                    altitude = 1.337, 
                    minimum_elevation = 1.337, 
                    station_mask = spacetower_measurement_generation_python_client.models.station_mask.StationMask(
                        station_mask = [
                            1.337
                            ], ), ),
                earth_ellipsoid_configuration = spacetower_measurement_generation_python_client.models.earth_ellipsoid_configuration.EarthEllipsoidConfiguration(
                    earth_fixed_frame_id = 'ITRF2020', 
                    ellipsoid_id = 'WGS84', 
                    include_tidal_effects_in_eop_interpolation = True, ),
                reference_frame_id = 'EME2000'
            )
        else:
            return RaDecMeasurementsRequest(
                ground_station = spacetower_measurement_generation_python_client.models.ground_station.GroundStation(
                    name = '', 
                    latitude = 1.337, 
                    longitude = 1.337, 
                    altitude = 1.337, 
                    minimum_elevation = 1.337, 
                    station_mask = spacetower_measurement_generation_python_client.models.station_mask.StationMask(
                        station_mask = [
                            1.337
                            ], ), ),
                reference_frame_id = 'EME2000',
        )
        """

    def testRaDecMeasurementsRequest(self):
        """Test RaDecMeasurementsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
