# coding: utf-8

"""
    Measurements Generation API

    Measurements Generation API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spacetower_measurement_generation_python_client.models.orbital_parameter_type import OrbitalParameterType

class TestOrbitalParameterType(unittest.TestCase):
    """OrbitalParameterType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOrbitalParameterType(self):
        """Test OrbitalParameterType"""
        # inst = OrbitalParameterType()

if __name__ == '__main__':
    unittest.main()
