
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-01-07T13:19:04+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "0097ef408d763afc8c65d4f9af74eb1c62e289b3",
 "version": "1.8.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
