# coding: utf-8

"""
    Bluefin API

    Bluefin API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class SubscriptionType(str, Enum):
    """
    Indicates the type of subscription action.
    """

    """
    allowed enum values
    """
    SUBSCRIBE = 'Subscribe'
    UNSUBSCRIBE = 'Unsubscribe'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of SubscriptionType from a JSON string"""
        return cls(json.loads(json_str))


