
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-01-08T09:24:20-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "5f499fc9a25f0d76dac356539521460d6c806197",
 "version": "5.2.12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
