# coding: utf-8

"""
    Bluefin API

    Bluefin API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from bluefin_pro_api_client.api.exchange_api import ExchangeApi


class TestExchangeApi(unittest.IsolatedAsyncioTestCase):
    """ExchangeApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = ExchangeApi()

    async def asyncTearDown(self) -> None:
        pass

    async def test_get_candlestick_data(self) -> None:
        """Test case for get_candlestick_data

        Kline/candlestick data.
        """
        pass

    async def test_get_exchange_info(self) -> None:
        """Test case for get_exchange_info

        Get exchange information
        """
        pass

    async def test_get_funding_rate_history(self) -> None:
        """Test case for get_funding_rate_history

        Get funding rate history
        """
        pass

    async def test_get_market_ticker(self) -> None:
        """Test case for get_market_ticker

        Aggregated market ticker information
        """
        pass

    async def test_get_orderbook_depth(self) -> None:
        """Test case for get_orderbook_depth

        Orderbook depth
        """
        pass

    async def test_get_recent_trades(self) -> None:
        """Test case for get_recent_trades

        Recent trades list
        """
        pass


if __name__ == '__main__':
    unittest.main()
