# coding: utf-8

"""
    Bluefin API

    Bluefin API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from bluefin_pro_api_client.models.position import Position

class TestPosition(unittest.TestCase):
    """Position unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Position:
        """Test Position
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Position`
        """
        model = Position()
        if include_optional:
            return Position(
                market_address = '',
                avg_entry_price_e9 = '400000000000',
                leverage_e9 = '100000000000',
                liquidation_price_e9 = '0',
                mark_price_e9 = '667950671178',
                notional_value_e9 = '0',
                max_notional_value_e9 = '20000000000000',
                position_size_e9 = '100000000',
                unrealized_pnl_e9 = '-1000000000',
                position_side = 'LONG',
                initial_margin_e9 = '0',
                maint_margin_e9 = '0',
                is_isolated = True,
                isolated_margin_e9 = '1000000000',
                last_updated_at_utc_millis = 1733899435274
            )
        else:
            return Position(
                market_address = '',
                avg_entry_price_e9 = '400000000000',
                leverage_e9 = '100000000000',
                liquidation_price_e9 = '0',
                mark_price_e9 = '667950671178',
                notional_value_e9 = '0',
                max_notional_value_e9 = '20000000000000',
                position_size_e9 = '100000000',
                unrealized_pnl_e9 = '-1000000000',
                position_side = 'LONG',
                initial_margin_e9 = '0',
                maint_margin_e9 = '0',
                is_isolated = True,
                isolated_margin_e9 = '1000000000',
                last_updated_at_utc_millis = 1733899435274,
        )
        """

    def testPosition(self):
        """Test Position"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
