# coding: utf-8

"""
    Bluefin API

    Bluefin API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from bluefin_pro_api_client.models.account_position_update import AccountPositionUpdate

class TestAccountPositionUpdate(unittest.TestCase):
    """AccountPositionUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AccountPositionUpdate:
        """Test AccountPositionUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AccountPositionUpdate`
        """
        model = AccountPositionUpdate()
        if include_optional:
            return AccountPositionUpdate(
                market_address = '',
                avg_entry_price_e9 = '',
                leverage_e9 = '',
                liquidation_price_e9 = '',
                mark_price_e9 = '',
                notional_value_e9 = '',
                max_notional_value_e9 = '',
                size_e9 = '',
                unrealized_pnl_e9 = '',
                side = 'LONG',
                initial_margin_e9 = '',
                maintenance_margin_e9 = '',
                is_isolated = True,
                isolated_margin_e9 = '',
                updated_at_utc_millis = 56
            )
        else:
            return AccountPositionUpdate(
                market_address = '',
                avg_entry_price_e9 = '',
                leverage_e9 = '',
                liquidation_price_e9 = '',
                mark_price_e9 = '',
                notional_value_e9 = '',
                max_notional_value_e9 = '',
                size_e9 = '',
                unrealized_pnl_e9 = '',
                side = 'LONG',
                initial_margin_e9 = '',
                maintenance_margin_e9 = '',
                is_isolated = True,
                isolated_margin_e9 = '',
                updated_at_utc_millis = 56,
        )
        """

    def testAccountPositionUpdate(self):
        """Test AccountPositionUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
