# coding: utf-8

"""
    Bluefin API

    Bluefin API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from bluefin_pro_api_client.models.trade_side import TradeSide

class TestTradeSide(unittest.TestCase):
    """TradeSide unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTradeSide(self):
        """Test TradeSide"""
        # inst = TradeSide()

if __name__ == '__main__':
    unittest.main()
