"""
This type stub file was generated by pyright.
"""

from pydantic import BaseModel

class GithubNamedUserContext(BaseModel):
    """Represents a GitHub user parsed from a webhook payload"""
    login: str
    email: str
    @classmethod
    def from_payload(cls, payload: dict) -> GithubNamedUserContext:
        ...
    


