from .hash import uSwidHash as uSwidHash, uSwidHashAlg as uSwidHashAlg
from .problem import uSwidProblem as uSwidProblem
from _typeshed import Incomplete

class uSwidPayload:
    name: Incomplete
    size: Incomplete
    def __init__(self, name: str | None = None, size: int | None = None) -> None: ...
    def add_hash(self, ihash: uSwidHash) -> None: ...
    def remove_hash(self, alg_id: uSwidHashAlg) -> None: ...
    @property
    def hashes(self) -> list[uSwidHash]: ...
    def ensure_from_filename(self, fn: str) -> None: ...
    def problems(self) -> list[uSwidProblem]: ...
