DEFAULT_CONFIG_BASENAME = "xrlint_config"

DEFAULT_CONFIG_FILE_YAML = f"{DEFAULT_CONFIG_BASENAME}.yaml"
DEFAULT_CONFIG_FILE_JSON = f"{DEFAULT_CONFIG_BASENAME}.json"
DEFAULT_CONFIG_FILE_PY = f"{DEFAULT_CONFIG_BASENAME}.py"

DEFAULT_CONFIG_FILES = [
    DEFAULT_CONFIG_FILE_YAML,
    DEFAULT_CONFIG_FILE_JSON,
    DEFAULT_CONFIG_FILE_PY,
]

DEFAULT_OUTPUT_FORMAT = "simple"
DEFAULT_MAX_WARNINGS = 5

INIT_CONFIG_YAML = "- recommended\n"

DEFAULT_GLOBAL_FILES = ["**/*.zarr", "**/*.nc"]
DEFAULT_GLOBAL_IGNORES = [".git", "node_modules"]
