
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-01-08T15:19:37+1100",
 "dirty": false,
 "error": null,
 "full-revisionid": "36c03744d5368d1d072a1d37eb4cccb6294263a3",
 "version": "0.0.57.dev4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
