
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-01-07T14:00:14+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "e71d779bf1100ec178a1f4cbd2acdb246496da19",
 "version": "2.4.43"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
