# Generated by Django 5.0.9 on 2025-01-07 10:01

import django.db.models.deletion
import django.db.models.lookups
import uuid
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import ProjectState

class ConditionalDatabaseOperation(migrations.SeparateDatabaseAndState):
    def __init__(self, operations):
        super().__init__(database_operations=operations, state_operations=operations)

    def database_forwards(
            self, app_label: str, schema_editor: BaseDatabaseSchemaEditor,
            from_state: ProjectState, to_state: ProjectState
    ) -> None:
        manipulate_database = True
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(
                "SELECT EXISTS ( SELECT 1 FROM pg_tables WHERE tablename = 'wise_market_symbol' )")
            if next(cursor.cursor)[0]:
                manipulate_database = False
        if manipulate_database:
            super().database_forwards(app_label, schema_editor,
                                      from_state, to_state)


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    _operations = [
        migrations.CreateModel(
            name="Exchange",
            fields=[
                (
                    "key",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("name", models.CharField(max_length=256, unique=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Market",
            fields=[
                (
                    "key",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("name", models.CharField(max_length=256, unique=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Network",
            fields=[
                (
                    "key",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("name", models.CharField(db_index=True, max_length=256, unique=True)),
                ("slug", models.CharField(max_length=256, unique=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Symbol",
            fields=[
                (
                    "key",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("name", models.CharField(max_length=256)),
                ("slug", models.CharField(max_length=256, unique=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ExchangeMarket",
            fields=[
                (
                    "key",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "exchange",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wise_market.exchange",
                    ),
                ),
                (
                    "market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wise_market.market",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "unique_together": {("exchange", "market")},
            },
        ),
        migrations.CreateModel(
            name="Pair",
            fields=[
                (
                    "key",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("slug", models.CharField(max_length=256, unique=True)),
                ("name", models.CharField(max_length=256)),
                (
                    "base",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="base_pairs",
                        to="wise_market.symbol",
                    ),
                ),
                (
                    "quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quote_pairs",
                        to="wise_market.symbol",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "unique_together": {("base", "quote")},
            },
        ),
        migrations.CreateModel(
            name="NetworkSymbolBinding",
            fields=[
                (
                    "key",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("decimals", models.IntegerField(default=18)),
                ("step_size", models.FloatField(default=1e-18)),
                (
                    "type",
                    models.CharField(
                        choices=[("COIN", "Native Coin"), ("TOKEN", "Utility Token")],
                        db_index=True,
                        default="TOKEN",
                        max_length=64,
                    ),
                ),
                (
                    "network",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="symbol_bindings",
                        to="wise_market.network",
                    ),
                ),
                (
                    "symbol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="network_bindings",
                        to="wise_market.symbol",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "key",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("SYMBOL", "SYMBOL"), ("PAIR", "PAIR")], max_length=32
                    ),
                ),
                (
                    "pair",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wise_market.pair",
                    ),
                ),
                (
                    "symbol",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wise_market.symbol",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ExchangeMarketPairBinding",
            fields=[
                (
                    "key",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("price_decimals", models.IntegerField()),
                ("quantity_decimals", models.IntegerField()),
                ("price_step_size", models.FloatField()),
                ("quantity_step_size", models.FloatField()),
                ("min_notional", models.FloatField()),
                (
                    "exchange_market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pair_bindings",
                        to="wise_market.exchangemarket",
                    ),
                ),
                (
                    "pair",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exchange_market_bindings",
                        to="wise_market.pair",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "unique_together": {("exchange_market", "pair")},
            },
        ),
        migrations.AddConstraint(
            model_name="networksymbolbinding",
            constraint=models.UniqueConstraint(
                models.F("network"),
                models.F("symbol"),
                name="network_symbol_binding_unique_network_symbol",
            ),
        ),
        migrations.AddConstraint(
            model_name="networksymbolbinding",
            constraint=models.UniqueConstraint(
                condition=models.Q(("type", "COIN")),
                fields=("network",),
                name="network_symbol_binding_unique_network_native_coin",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="networksymbolbinding",
            unique_together={("symbol", "network")},
        ),
        migrations.AddConstraint(
            model_name="asset",
            constraint=models.CheckConstraint(
                check=models.ExpressionWrapper(
                    models.Q(
                        django.db.models.lookups.Exact(
                            lhs=models.Func(
                                "symbol",
                                "pair",
                                function="num_nonnulls",
                                output_field=models.IntegerField(),
                            ),
                            rhs=models.Value(1),
                        )
                    ),
                    output_field=models.BooleanField(),
                ),
                name="exactly_one_non_null__symbol__pair",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="asset",
            unique_together={("type", "symbol", "pair")},
        ),
    ]


    operations = [
        ConditionalDatabaseOperation(operations=_operations)
    ]

