SITES = [
    # Social Networks
    {"name": "Facebook", "url": "https://www.facebook.com/{}", "category": "social", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "Instagram", "url": "https://www.instagram.com/{}", "category": "social", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "X (formerly Twitter)", "url": "https://x.com/{}", "category": "social", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "LinkedIn", "url": "https://www.linkedin.com/in/{}", "category": "social", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "TikTok", "url": "https://www.tiktok.com/@{}", "category": "social", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "Threads", "url": "https://www.threads.net/@{}", "category": "social", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "Pinterest", "url": "https://www.pinterest.com/{}", "category": "social", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "Reddit", "url": "https://www.reddit.com/user/{}", "category": "social", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "Mastodon", "url": "https://{}/", "category": "social", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "Discord", "url": "https://discord.com/users/{}", "category": "social", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "Telegram", "url": "https://t.me/{}", "category": "social", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "WhatsApp", "url": "https://wa.me/{}", "category": "social", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "WeChat", "url": "https://wechat.com/{}", "category": "social", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "Signal", "url": "https://signal.me/#p/{}", "category": "social", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "BeReal", "url": "https://bere.al/{}", "category": "social", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "Lemon8", "url": "https://lemon8-app.com/@{}", "category": "social", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "Bluesky", "url": "https://bsky.app/profile/{}", "category": "social", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "Post", "url": "https://post.news/{}", "category": "social", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "Nostr", "url": "https://nostr.com/{}", "category": "social", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "Pebble", "url": "https://pebble.social/{}", "category": "social", "method": "status", "error_code": 404, "success_code": 200, "marker": None},

    # Developer Platforms
    {"name": "GitHub", "url": "https://github.com/{}", "category": "dev", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "GitLab", "url": "https://gitlab.com/{}", "category": "dev", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "Bitbucket", "url": "https://bitbucket.org/{}", "category": "dev", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "Stack Overflow", "url": "https://stackoverflow.com/users/{}", "category": "dev", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "Stack Exchange", "url": "https://stackexchange.com/users/{}", "category": "dev", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "Dev.to", "url": "https://dev.to/{}", "category": "dev", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "CodePen", "url": "https://codepen.io/{}", "category": "dev", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "Replit", "url": "https://replit.com/@{}", "category": "dev", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
     {"name": "NuGet", "url": "https://www.nuget.org/profiles/{}", "category": "dev", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "Packagist", "url": "https://packagist.org/users/{}", "category": "dev", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "PyPI", "url": "https://pypi.org/user/{}", "category": "dev", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "npm", "url": "https://www.npmjs.com/~{}", "category": "dev", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "Docker Hub", "url": "https://hub.docker.com/u/{}", "category": "dev", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "Rust Crates.io", "url": "https://crates.io/users/{}", "category": "dev", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "Go Packages", "url": "https://pkg.go.dev/{}", "category": "developer", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "RubyGems", "url": "https://rubygems.org/profiles/{}", "category": "dev", "method": "status", "error_code": 404, "success_code": 200, "marker": None},

    # Gaming Platforms
    {"name": "Steam", "url": "https://steamcommunity.com/id/{}", "category": "gaming", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "Epic Games", "url": "https://www.epicgames.com/id/{}", "category": "gaming", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "PlayStation Network", "url": "https://psnprofiles.com/{}", "category": "gaming", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "Xbox", "url": "https://account.xbox.com/en-us/profile?gamerTag={}", "category": "gaming", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "Nintendo", "url": "https://my.nintendo.com/{}", "category": "gaming", "method": "status", "error_code": 404, "success_code": 200, "marker": None},

    # Job Platforms
    {"name": "AngelList", "url": "https://angel.co/u/{}", "category": "job", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "HackerRank", "url": "https://www.hackerrank.com/{}", "category": "job", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "Kaggle", "url": "https://www.kaggle.com/{}", "category": "job", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "Indeed", "url": "https://my.indeed.com/p/{}", "category": "job", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "Glassdoor", "url": "https://www.glassdoor.com/profile/{}/", "category": "job", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    # Streaming Platforms
    {"name": "YouTube", "url": "https://www.youtube.com/{}", "category": "streaming", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "Twitch", "url": "https://www.twitch.tv/{}", "category": "streaming", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "Spotify", "url": "https://open.spotify.com/user/{}", "category": "streaming", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "SoundCloud", "url": "https://soundcloud.com/{}", "category": "streaming", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "Apple Music", "url": "https://music.apple.com/profile/{}", "category": "streaming", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "Deezer", "url": "https://www.deezer.com/profile/{}", "category": "streaming", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "Tidal", "url": "https://tidal.com/browse/user/{}", "category": "streaming", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "Mixcloud", "url": "https://www.mixcloud.com/{}", "category": "streaming", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "Pandora", "url": "https://www.pandora.com/profile/{}", "category": "streaming", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "Bandcamp", "url": "https://bandcamp.com/{}", "category": "streaming", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "Vimeo", "url": "https://vimeo.com/{}", "category": "streaming", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "Dailymotion", "url": "https://www.dailymotion.com/{}", "category": "streaming", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "Rumble", "url": "https://rumble.com/user/{}", "category": "streaming", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "LiveLeak", "url": "https://www.liveleak.com/user/{}", "category": "streaming", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "Metacafe", "url": "https://www.metacafe.com/channels/{}", "category": "streaming", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "BitChute", "url": "https://www.bitchute.com/channel/{}", "category": "streaming", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "DTube", "url": "https://d.tube/#!/c/{}", "category": "streaming", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "Streamable", "url": "https://streamable.com/{}", "category": "streaming", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "Caffeine", "url": "https://www.caffeine.tv/{}", "category": "streaming", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "Smashcast", "url": "https://www.smashcast.tv/{}", "category": "streaming", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "DLive", "url": "https://dlive.tv/{}", "category": "streaming", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "Periscope", "url": "https://www.pscp.tv/{}", "category": "streaming", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "YouTube Gaming", "url": "https://gaming.youtube.com/channel/{}", "category": "streaming", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "Facebook Gaming", "url": "https://www.facebook.com/gaming/{}", "category": "streaming", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "Trovo", "url": "https://trovo.live/{}", "category": "streaming", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "OnlyFans", "url": "https://onlyfans.com/{}", "category": "streaming", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "Fansly", "url": "https://fansly.com/{}", "category": "streaming", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "Buy Me a Coffee", "url": "https://www.buymeacoffee.com/{}", "category": "streaming", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    # Forums
    {"name": "Quora", "url": "https://www.quora.com/profile/{}", "category": "forum", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "4chan", "url": "https://boards.4chan.org/{}", "category": "forum", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "9GAG", "url": "https://9gag.com/u/{}", "category": "forum", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "Imgur", "url": "https://imgur.com/user/{}", "category": "forum", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "Flickr", "url": "https://www.flickr.com/people/{}", "category": "forum", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "DeviantArt", "url": "https://{}.deviantart.com", "category": "forum", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "Goodreads", "url": "https://www.goodreads.com/{}", "category": "forum", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "Letterboxd", "url": "https://letterboxd.com/{}", "category": "forum", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "MyAnimeList", "url": "https://myanimelist.net/profile/{}", "category": "forum", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "Gaia Online", "url": "https://www.gaiaonline.com/profiles/{}", "category": "forum", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "Wattpad", "url": "https://www.wattpad.com/user/{}", "category": "forum", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "Fanfiction.net", "url": "https://www.fanfiction.net/u/{}", "category": "forum", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "Archive of Our Own", "url": "https://archiveofourown.org/users/{}", "category": "forum", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    # PAYMENT
    {"name": "PayPal", "url": "https://paypal.me/{}", "category": "payment", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "Venmo", "url": "https://venmo.com/{}", "category": "payment", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "Cash App", "url": "https://cash.app/${}", "category": "payment", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "Stripe", "url": "https://stripe.com/{}", "category": "payment", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    # FREELANCE_MARKETPLACES
    {"name": "Fiverr", "url": "https://www.fiverr.com/{}", "category": "freelance", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "Upwork", "url": "https://www.upwork.com/freelancers/~{}", "category": "freelance", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "Behance", "url": "https://www.behance.net/{}", "category": "creative", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "Dribbble", "url": "https://dribbble.com/{}", "category": "creative", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "ArtStation", "url": "https://www.artstation.com/{}", "category": "creative", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "Gumroad", "url": "https://gumroad.com/{}", "category": "ecommerce", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "Shopify", "url": "https://{}.myshopify.com", "category": "ecommerce", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "Etsy", "url": "https://www.etsy.com/shop/{}", "category": "ecommerce", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "Product Hunt", "url": "https://www.producthunt.com/@{}", "category": "startup", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "Patreon", "url": "https://www.patreon.com/{}", "category": "creative", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "Kickstarter", "url": "https://www.kickstarter.com/profile/{}", "category": "crowdfunding", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "Indiegogo", "url": "https://www.indiegogo.com/individuals/{}", "category": "crowdfunding", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "GoFundMe", "url": "https://www.gofundme.com/f/{}", "category": "crowdfunding", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    # OTHER
    {"name": "Substack", "url": "https://{}.substack.com", "category": "blog", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "Google (Profile)", "url": "https://profiles.google.com/{}", "category": "profile", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "Microsoft (Profile)", "url": "https://account.microsoft.com/profile/{}", "category": "profile", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "Apple ID", "url": "https://appleid.apple.com/account/{}", "category": "profile", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "Slack", "url": "https://{}.slack.com", "category": "workspace", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "Trello", "url": "https://trello.com/{}", "category": "task", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "Notion", "url": "https://www.notion.so/{}", "category": "workspace", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "Airtable", "url": "https://airtable.com/{}", "category": "workspace", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "Zoom", "url": "https://zoom.us/profile/{}", "category": "profile", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "Skype", "url": "https://www.skype.com/{}", "category": "profile", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "WordPress.com", "url": "https://{}.wordpress.com", "category": "blog", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "Blogger", "url": "https://www.blogger.com/profile/{}", "category": "blog", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "Wix", "url": "https://{}.wixsite.com", "category": "website", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "Squarespace", "url": "https://{}.squarespace.com", "category": "website", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "Weebly", "url": "https://{}.weebly.com", "category": "website", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "Ghost", "url": "https://{}.ghost.io", "category": "blog", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "Medium", "url": "https://medium.com/@{}", "category": "blog", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "Tumblr", "url": "https://{}.tumblr.com", "category": "blog", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "LiveJournal", "url": "https://{}.livejournal.com", "category": "blog", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
    {"name": "Blogspot", "url": "https://{}.blogspot.com", "category": "blog", "method": "status", "error_code": 404, "success_code": 200, "marker": None},
]
