__name__ = "tinybird-cli"
__description__ = "Tinybird Command Line Tool"
__url__ = "https://www.tinybird.co/docs/cli/introduction.html"
__author__ = "Tinybird"
__author_email__ = "support@tinybird.co"
__version__ = "x.y.z"
__revision__ = "xxxxxxxxx"
