
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-01-08T11:50:47+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "881211dfc841853e1257535495a86d0d62a81d96",
 "version": "0+untagged.69.g881211d"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
