
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-01-08T18:42:34+0100",
 "dirty": true,
 "error": null,
 "full-revisionid": "bb2e00b43b5d1bf23eaa60cbce2e7857087cd37b",
 "version": "0.1.33"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
