# coding: utf-8

"""
    Orbit Extrapolation API

    Orbit Extrapolation API

    The version of the OpenAPI document: 2.4.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class OsculatingToMeanConversionTheory(str, Enum):
    """
    Options for converting an osculating state in a mean state according to the underlying theory.<br> Select:<br> - ```DSST_6X0``` for ```EQUINOCTIAL``` orbit type, using the Draper Semi-analytical Satellite theory with only the first six zonal harmonics - ```SGP4``` for ```KEPLERIAN``` orbit type, using the Simplified General Perturbations models associated with TLEs 
    """

    """
    allowed enum values
    """
    DSST_6_X0 = 'DSST_6X0'
    SGP4 = 'SGP4'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of OsculatingToMeanConversionTheory from a JSON string"""
        return cls(json.loads(json_str))


