# coding: utf-8

"""
    Orbit Extrapolation API

    Orbit Extrapolation API

    The version of the OpenAPI document: 2.4.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class TargetCelestialBody(str, Enum):
    """
    A celestial body that can be acquired in the Field of View
    """

    """
    allowed enum values
    """
    SUN = 'SUN'
    EARTH = 'EARTH'
    MOON = 'MOON'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of TargetCelestialBody from a JSON string"""
        return cls(json.loads(json_str))


