# coding: utf-8

"""
    Orbit Extrapolation API

    Orbit Extrapolation API

    The version of the OpenAPI document: 2.4.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spacetower_orbit_extrapolation_python_client.models.single_radiation_coefficient import SingleRadiationCoefficient

class TestSingleRadiationCoefficient(unittest.TestCase):
    """SingleRadiationCoefficient unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SingleRadiationCoefficient:
        """Test SingleRadiationCoefficient
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SingleRadiationCoefficient`
        """
        model = SingleRadiationCoefficient()
        if include_optional:
            return SingleRadiationCoefficient(
                reflection_coefficient = 0
            )
        else:
            return SingleRadiationCoefficient(
        )
        """

    def testSingleRadiationCoefficient(self):
        """Test SingleRadiationCoefficient"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
