# coding: utf-8

"""
    Orbit Extrapolation API

    Orbit Extrapolation API

    The version of the OpenAPI document: 2.4.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spacetower_orbit_extrapolation_python_client.models.attitude_ephemeris import AttitudeEphemeris

class TestAttitudeEphemeris(unittest.TestCase):
    """AttitudeEphemeris unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AttitudeEphemeris:
        """Test AttitudeEphemeris
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AttitudeEphemeris`
        """
        model = AttitudeEphemeris()
        if include_optional:
            return AttitudeEphemeris(
                dates = [
                    '2024-01-01T00:00Z'
                    ],
                description = [
                    spacetower_orbit_extrapolation_python_client.models.field_description.FieldDescription(
                        index = 56, 
                        name = '', 
                        label = '', 
                        units = '', )
                    ],
                inertial_frame_id = 'GCRF',
                attitude_representation_type = 'CARDAN_TNW_SAT'
            )
        else:
            return AttitudeEphemeris(
                dates = [
                    '2024-01-01T00:00Z'
                    ],
                attitude_representation_type = 'CARDAN_TNW_SAT',
        )
        """

    def testAttitudeEphemeris(self):
        """Test AttitudeEphemeris"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
