# coding: utf-8

"""
    Orbit Extrapolation API

    Orbit Extrapolation API

    The version of the OpenAPI document: 2.4.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spacetower_orbit_extrapolation_python_client.models.cardan_angle_ephemeris import CardanAngleEphemeris

class TestCardanAngleEphemeris(unittest.TestCase):
    """CardanAngleEphemeris unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CardanAngleEphemeris:
        """Test CardanAngleEphemeris
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CardanAngleEphemeris`
        """
        model = CardanAngleEphemeris()
        if include_optional:
            return CardanAngleEphemeris(
                data = [
                    [
                        1.337
                        ]
                    ]
            )
        else:
            return CardanAngleEphemeris(
                data = [
                    [
                        1.337
                        ]
                    ],
        )
        """

    def testCardanAngleEphemeris(self):
        """Test CardanAngleEphemeris"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
