# coding: utf-8

"""
    Orbit Extrapolation API

    Orbit Extrapolation API

    The version of the OpenAPI document: 2.4.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spacetower_orbit_extrapolation_python_client.models.battery_power_ephemeris import BatteryPowerEphemeris

class TestBatteryPowerEphemeris(unittest.TestCase):
    """BatteryPowerEphemeris unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BatteryPowerEphemeris:
        """Test BatteryPowerEphemeris
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BatteryPowerEphemeris`
        """
        model = BatteryPowerEphemeris()
        if include_optional:
            return BatteryPowerEphemeris(
                dates = [
                    '2024-01-01T00:00Z'
                    ],
                description = [
                    spacetower_orbit_extrapolation_python_client.models.field_description.FieldDescription(
                        index = 56, 
                        name = '', 
                        label = '', 
                        units = '', )
                    ],
                data = [
                    [
                        1.337
                        ]
                    ]
            )
        else:
            return BatteryPowerEphemeris(
                dates = [
                    '2024-01-01T00:00Z'
                    ],
                data = [
                    [
                        1.337
                        ]
                    ],
        )
        """

    def testBatteryPowerEphemeris(self):
        """Test BatteryPowerEphemeris"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
