# coding: utf-8

"""
    Orbit Extrapolation API

    Orbit Extrapolation API

    The version of the OpenAPI document: 2.4.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spacetower_orbit_extrapolation_python_client.models.maneuver_target_type import ManeuverTargetType

class TestManeuverTargetType(unittest.TestCase):
    """ManeuverTargetType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testManeuverTargetType(self):
        """Test ManeuverTargetType"""
        # inst = ManeuverTargetType()

if __name__ == '__main__':
    unittest.main()
