
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-01-08T20:25:35+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "e8cb2c2c625bdaa2e79a1a91fe56b46e1d084456",
 "version": "8.27.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
