# coding: utf-8

"""
    Bluefin API

    Bluefin API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from bluefin_pro_api_client.models.candlestick_update import CandlestickUpdate
from bluefin_pro_api_client.models.orderbook_diff_depth_update import OrderbookDiffDepthUpdate
from bluefin_pro_api_client.models.orderbook_partial_depth_update import OrderbookPartialDepthUpdate
from bluefin_pro_api_client.models.price_update import PriceUpdate
from bluefin_pro_api_client.models.recent_trade_updates import RecentTradeUpdates
from bluefin_pro_api_client.models.ticker_all_update import TickerAllUpdate
from bluefin_pro_api_client.models.ticker_update import TickerUpdate
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

MARKETSTREAMMESSAGEPAYLOAD_ONE_OF_SCHEMAS = ["CandlestickUpdate", "OrderbookDiffDepthUpdate", "OrderbookPartialDepthUpdate", "PriceUpdate", "RecentTradeUpdates", "TickerAllUpdate", "TickerUpdate"]

class MarketStreamMessagePayload(BaseModel):
    """
    The payload of the message, which varies based on the event type.
    """
    # data type: OrderbookDiffDepthUpdate
    oneof_schema_1_validator: Optional[OrderbookDiffDepthUpdate] = None
    # data type: OrderbookPartialDepthUpdate
    oneof_schema_2_validator: Optional[OrderbookPartialDepthUpdate] = None
    # data type: CandlestickUpdate
    oneof_schema_3_validator: Optional[CandlestickUpdate] = None
    # data type: PriceUpdate
    oneof_schema_4_validator: Optional[PriceUpdate] = None
    # data type: PriceUpdate
    oneof_schema_5_validator: Optional[PriceUpdate] = None
    # data type: PriceUpdate
    oneof_schema_6_validator: Optional[PriceUpdate] = None
    # data type: RecentTradeUpdates
    oneof_schema_7_validator: Optional[RecentTradeUpdates] = None
    # data type: TickerUpdate
    oneof_schema_8_validator: Optional[TickerUpdate] = None
    # data type: TickerAllUpdate
    oneof_schema_9_validator: Optional[TickerAllUpdate] = None
    actual_instance: Optional[Union[CandlestickUpdate, OrderbookDiffDepthUpdate, OrderbookPartialDepthUpdate, PriceUpdate, RecentTradeUpdates, TickerAllUpdate, TickerUpdate]] = None
    one_of_schemas: Set[str] = { "CandlestickUpdate", "OrderbookDiffDepthUpdate", "OrderbookPartialDepthUpdate", "PriceUpdate", "RecentTradeUpdates", "TickerAllUpdate", "TickerUpdate" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    discriminator_value_class_map: Dict[str, str] = {
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = MarketStreamMessagePayload.model_construct()
        error_messages = []
        match = 0
        # validate data type: OrderbookDiffDepthUpdate
        if not isinstance(v, OrderbookDiffDepthUpdate):
            error_messages.append(f"Error! Input type `{type(v)}` is not `OrderbookDiffDepthUpdate`")
        else:
            match += 1
        # validate data type: OrderbookPartialDepthUpdate
        if not isinstance(v, OrderbookPartialDepthUpdate):
            error_messages.append(f"Error! Input type `{type(v)}` is not `OrderbookPartialDepthUpdate`")
        else:
            match += 1
        # validate data type: CandlestickUpdate
        if not isinstance(v, CandlestickUpdate):
            error_messages.append(f"Error! Input type `{type(v)}` is not `CandlestickUpdate`")
        else:
            match += 1
        # validate data type: PriceUpdate
        if not isinstance(v, PriceUpdate):
            error_messages.append(f"Error! Input type `{type(v)}` is not `PriceUpdate`")
        else:
            match += 1
        # validate data type: PriceUpdate
        if not isinstance(v, PriceUpdate):
            error_messages.append(f"Error! Input type `{type(v)}` is not `PriceUpdate`")
        else:
            match += 1
        # validate data type: PriceUpdate
        if not isinstance(v, PriceUpdate):
            error_messages.append(f"Error! Input type `{type(v)}` is not `PriceUpdate`")
        else:
            match += 1
        # validate data type: RecentTradeUpdates
        if not isinstance(v, RecentTradeUpdates):
            error_messages.append(f"Error! Input type `{type(v)}` is not `RecentTradeUpdates`")
        else:
            match += 1
        # validate data type: TickerUpdate
        if not isinstance(v, TickerUpdate):
            error_messages.append(f"Error! Input type `{type(v)}` is not `TickerUpdate`")
        else:
            match += 1
        # validate data type: TickerAllUpdate
        if not isinstance(v, TickerAllUpdate):
            error_messages.append(f"Error! Input type `{type(v)}` is not `TickerAllUpdate`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in MarketStreamMessagePayload with oneOf schemas: CandlestickUpdate, OrderbookDiffDepthUpdate, OrderbookPartialDepthUpdate, PriceUpdate, RecentTradeUpdates, TickerAllUpdate, TickerUpdate. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in MarketStreamMessagePayload with oneOf schemas: CandlestickUpdate, OrderbookDiffDepthUpdate, OrderbookPartialDepthUpdate, PriceUpdate, RecentTradeUpdates, TickerAllUpdate, TickerUpdate. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into OrderbookDiffDepthUpdate
        try:
            instance.actual_instance = OrderbookDiffDepthUpdate.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into OrderbookPartialDepthUpdate
        try:
            instance.actual_instance = OrderbookPartialDepthUpdate.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into CandlestickUpdate
        try:
            instance.actual_instance = CandlestickUpdate.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into PriceUpdate
        try:
            instance.actual_instance = PriceUpdate.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into PriceUpdate
        try:
            instance.actual_instance = PriceUpdate.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into PriceUpdate
        try:
            instance.actual_instance = PriceUpdate.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into RecentTradeUpdates
        try:
            instance.actual_instance = RecentTradeUpdates.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into TickerUpdate
        try:
            instance.actual_instance = TickerUpdate.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into TickerAllUpdate
        try:
            instance.actual_instance = TickerAllUpdate.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into MarketStreamMessagePayload with oneOf schemas: CandlestickUpdate, OrderbookDiffDepthUpdate, OrderbookPartialDepthUpdate, PriceUpdate, RecentTradeUpdates, TickerAllUpdate, TickerUpdate. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into MarketStreamMessagePayload with oneOf schemas: CandlestickUpdate, OrderbookDiffDepthUpdate, OrderbookPartialDepthUpdate, PriceUpdate, RecentTradeUpdates, TickerAllUpdate, TickerUpdate. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], CandlestickUpdate, OrderbookDiffDepthUpdate, OrderbookPartialDepthUpdate, PriceUpdate, RecentTradeUpdates, TickerAllUpdate, TickerUpdate]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


