# coding: utf-8

"""
    Orbit Extrapolation API

    Orbit Extrapolation API

    The version of the OpenAPI document: 2.4.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spacetower_orbit_extrapolation_python_client.models.geodetic_ephemeris_request import GeodeticEphemerisRequest

class TestGeodeticEphemerisRequest(unittest.TestCase):
    """GeodeticEphemerisRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GeodeticEphemerisRequest:
        """Test GeodeticEphemerisRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GeodeticEphemerisRequest`
        """
        model = GeodeticEphemerisRequest()
        if include_optional:
            return GeodeticEphemerisRequest(
                time_grid_configuration = spacetower_orbit_extrapolation_python_client.models.ephemeris_time_grid_configuration.EphemerisTimeGridConfiguration(
                    grid_type = 'UNIFORM', ),
                start_date = '2024-01-01T00:00Z',
                end_date = '2024-01-01T00:00Z'
            )
        else:
            return GeodeticEphemerisRequest(
        )
        """

    def testGeodeticEphemerisRequest(self):
        """Test GeodeticEphemerisRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
