# coding: utf-8

"""
    Orbit Extrapolation API

    Orbit Extrapolation API

    The version of the OpenAPI document: 2.4.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spacetower_orbit_extrapolation_python_client.models.event_generation_requests_with_attitude import EventGenerationRequestsWithAttitude

class TestEventGenerationRequestsWithAttitude(unittest.TestCase):
    """EventGenerationRequestsWithAttitude unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EventGenerationRequestsWithAttitude:
        """Test EventGenerationRequestsWithAttitude
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EventGenerationRequestsWithAttitude`
        """
        model = EventGenerationRequestsWithAttitude()
        if include_optional:
            return EventGenerationRequestsWithAttitude(
                orbital_event_request = None,
                station_event_request = None,
                conjunction_event_request = None,
                secondary_object_event_request = None,
                field_of_view_event_request = None
            )
        else:
            return EventGenerationRequestsWithAttitude(
        )
        """

    def testEventGenerationRequestsWithAttitude(self):
        """Test EventGenerationRequestsWithAttitude"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
