# coding: utf-8

"""
    Orbit Extrapolation API

    Orbit Extrapolation API

    The version of the OpenAPI document: 2.4.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spacetower_orbit_extrapolation_python_client.models.terrestrial_relative_position_ephemeris_request import TerrestrialRelativePositionEphemerisRequest

class TestTerrestrialRelativePositionEphemerisRequest(unittest.TestCase):
    """TerrestrialRelativePositionEphemerisRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TerrestrialRelativePositionEphemerisRequest:
        """Test TerrestrialRelativePositionEphemerisRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TerrestrialRelativePositionEphemerisRequest`
        """
        model = TerrestrialRelativePositionEphemerisRequest()
        if include_optional:
            return TerrestrialRelativePositionEphemerisRequest(
                time_grid_configuration = spacetower_orbit_extrapolation_python_client.models.ephemeris_time_grid_configuration.EphemerisTimeGridConfiguration(
                    grid_type = 'UNIFORM', ),
                start_date = '2024-01-01T00:00Z',
                end_date = '2024-01-01T00:00Z',
                ground_locations = [
                    spacetower_orbit_extrapolation_python_client.models.ground_location.GroundLocation(
                        name = '', 
                        longitude = 1.337, 
                        latitude = 1.337, 
                        altitude = 1.337, )
                    ]
            )
        else:
            return TerrestrialRelativePositionEphemerisRequest(
                ground_locations = [
                    spacetower_orbit_extrapolation_python_client.models.ground_location.GroundLocation(
                        name = '', 
                        longitude = 1.337, 
                        latitude = 1.337, 
                        altitude = 1.337, )
                    ],
        )
        """

    def testTerrestrialRelativePositionEphemerisRequest(self):
        """Test TerrestrialRelativePositionEphemerisRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
