# coding: utf-8

"""
    Orbit Extrapolation API

    Orbit Extrapolation API

    The version of the OpenAPI document: 2.4.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spacetower_orbit_extrapolation_python_client.models.battery_model import BatteryModel

class TestBatteryModel(unittest.TestCase):
    """BatteryModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BatteryModel:
        """Test BatteryModel
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BatteryModel`
        """
        model = BatteryModel()
        if include_optional:
            return BatteryModel(
                nominal_capacity = 0.0,
                depth_of_discharge = 1.337,
                initial_charge = 0.0,
                minimum_charge_when_firing = 0.0
            )
        else:
            return BatteryModel(
                nominal_capacity = 0.0,
                depth_of_discharge = 1.337,
                initial_charge = 0.0,
        )
        """

    def testBatteryModel(self):
        """Test BatteryModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
