# coding: utf-8

"""
    Orbit Extrapolation API

    Orbit Extrapolation API

    The version of the OpenAPI document: 2.4.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spacetower_orbit_extrapolation_python_client.models.local_frame_attitude_law import LocalFrameAttitudeLaw

class TestLocalFrameAttitudeLaw(unittest.TestCase):
    """LocalFrameAttitudeLaw unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LocalFrameAttitudeLaw:
        """Test LocalFrameAttitudeLaw
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LocalFrameAttitudeLaw`
        """
        model = LocalFrameAttitudeLaw()
        if include_optional:
            return LocalFrameAttitudeLaw(
                local_frame_id = 'LVLH_ROTATING',
                rotation_order = 'XYZ',
                rotation_convention = 'FRAME_TRANSFORM',
                first_angle = 1.337,
                second_angle = 1.337,
                third_angle = 1.337
            )
        else:
            return LocalFrameAttitudeLaw(
        )
        """

    def testLocalFrameAttitudeLaw(self):
        """Test LocalFrameAttitudeLaw"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
