# coding: utf-8

"""
    Orbit Extrapolation API

    Orbit Extrapolation API

    The version of the OpenAPI document: 2.4.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spacetower_orbit_extrapolation_python_client.models.mean_osculating_orbit_type import MeanOsculatingOrbitType

class TestMeanOsculatingOrbitType(unittest.TestCase):
    """MeanOsculatingOrbitType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMeanOsculatingOrbitType(self):
        """Test MeanOsculatingOrbitType"""
        # inst = MeanOsculatingOrbitType()

if __name__ == '__main__':
    unittest.main()
