
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-01-06T10:03:17+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "dc610188751fa7a2bae9b33f8940361352ee527b",
 "version": "1.31.0.post0.dev54"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
