
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-01-06T23:17:33+0100",
 "dirty": true,
 "error": null,
 "full-revisionid": "503acd3ed094435e1378290693cd018cad653bf3",
 "version": "0.0.32"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
