DARK_GREEN = '#265d29'
DARK_RED = '#8a3b3a'
LIGHT_ORANGE = '#e3a68c'

# COLOURS
WHITE = '#FFFFFF'
BLACK = '#000000'
GREY = '#707070'

# INDICATOR COLOURS
MAIN_PINK = '#dcc2fe'
MAIN_BLUE = '#5fadfb'
MAIN_PURPLE = '#615efa'
RED = '#E73E3A'
LIME_GREEN = '#4DD753'
YELLOW_LIME = '#b9fd00'
LIGHT_SKY_BLUE = '#92c4da'
SKY_BLUE = '#06AED5'
ORANGE = '#E75826'

# CHART COLOURS
BACKGROUND = WHITE
BULLISH_CANDLE_OUTLINE = GREY
BULLISH_CANDLE_FILL = GREY
BEARISH_CANDLE_OUTLINE = GREY
BEARISH_CANDLE_FILL = BACKGROUND
INDICATOR_LINE = MAIN_PURPLE

# HOME PAGE
CHART_REFRESH_INTERVAL_MS = 500
MIN_CANDLES = 200
MAX_CANDLES = 1000

# INDICATORS
SMA_FAST = 9
SMA_SLOW = 21
SMA = 200

BOLLINGER_BANDS_PERIOD = 5
