# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: backtest.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from typing import List

import betterproto


@dataclass(eq=False, repr=False)
class BacktestEvalTrigger(betterproto.Message):
    company_id: int = betterproto.int64_field(1)
    application_id: int = betterproto.int64_field(2)
    session_ids: List[str] = betterproto.string_field(3)
