# coding: utf-8

"""
    Orbital State Management API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class AtmosphereType(str, Enum):
    """
    Possible choices for the atmospheric model
    """

    """
    allowed enum values
    """
    HARRIS_PRIESTER = 'HARRIS_PRIESTER'
    NRLMSISE_00 = 'NRLMSISE_00'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AtmosphereType from a JSON string"""
        return cls(json.loads(json_str))


