# coding: utf-8

"""
    Measurements Generation API

    Measurements Generation API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class NoiseFrameId(str, Enum):
    """
    Noise frame
    """

    """
    allowed enum values
    """
    GLOBAL = 'GLOBAL'
    QSW_FROZEN = 'QSW_FROZEN'
    QSW_ROTATING = 'QSW_ROTATING'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of NoiseFrameId from a JSON string"""
        return cls(json.loads(json_str))


