configFormat='pvplot'
TITLE="Blue Injection Scope"
POLLPERIOD 0
MINPOLLPERIOD 0
POLLBEFOREASYNC 1
AVERAGETYPE  none
LOGFORMAT logger
LOGPERIODSEC 0
LOGMETHOD continuous
LOGDESCRIPTION ""
LOGCORRELATION NOTREQUIRED
FILLDATA   YES
LOGTREEPATH  /operations/app_store/RunData/currentFill/
PREFERREDLOGDISPLAY Snapshot
XLABEL "Time (us)"
YLABEL "kV  (at 1 V/div)"
DATASTAMPTYPE WCTPERIOD
WCTCORRPERIOD_MSEC 1000
WCTCORRWINDOW_MSEC 1000
SYNCHRONIZED 0
YMINAUTOSCALE 2
YMAXAUTOSCALE 2
YLOGAXIS 0
Y2LABEL ""
Y2MINAUTOSCALE 2
Y2MAXAUTOSCALE 2
Y2LOGAXIS 0
ERRORBARS 0
FONTTYPE Medium
KEEPPREVIOUS 0
SNAPREFRESHMODE 2
SNAPSUBCYCLES 1 2 3 4 5 6 7 8 9 10 

dev='tek5Scope.inject7W_blu:'

#STATIC Time= 1.e6*device(tek5Scope.inject7W_blu:tAxis[*])
DOCKS = 
[
    {f'Module{i}':f'device({dev}c{i}WaveforM:value[*])*a+b' for i in [1,2,3,4]} 
]
