# -*- coding: utf-8 -*-
"""empty message

Revision ID: poppy_pop_0002_version_num
Revises: poppy_pop_0001_initial
Create Date: 2021-11-22 18:02:51.101356

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "poppy_pop_0002_version_num"
down_revision = "poppy_pop_0001_initial"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "alembic_version", "version_num", type_=sa.String(length=256), schema="public"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "alembic_version", "version_num", type_=sa.String(length=32), schema="public"
    )
    # ### end Alembic public ###
