
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-01-06T16:05:23+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "249486840b35a11c1125ffb6a9fda7dad9a0987b",
 "version": "1.31.0.post0.dev64"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
