"""
This type stub file was generated by pyright.
"""

from pydantic import BaseModel
from app.utils.codemod.codemod_writer_decorators import apidoc

@apidoc
class PROptions(BaseModel):
    """Options for generating a PR."""
    title: str = ...
    body: str = ...
    labels: list[str] = ...
    force_push_head_branch: bool = ...


