# coding: utf-8

"""
    Orbit Extrapolation API

    Orbit Extrapolation API

    The version of the OpenAPI document: 2.4.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class EventDetectionType(str, Enum):
    """
    Defines the effect of events on propagation
    """

    """
    allowed enum values
    """
    LOG_ALL = 'LOG_ALL'
    STOP_ON_FIRST_OCCURRENCE = 'STOP_ON_FIRST_OCCURRENCE'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of EventDetectionType from a JSON string"""
        return cls(json.loads(json_str))


