# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: rates.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass

import betterproto


@dataclass(eq=False, repr=False)
class RateLimits(betterproto.Message):
    id: int = betterproto.int64_field(1)
    date_created: int = betterproto.int64_field(2)
    company_id: int = betterproto.int64_field(3)
    requests_day: int = betterproto.int64_field(4)
    requests_minute: int = betterproto.int64_field(5)
    tokens_day: int = betterproto.int64_field(6)
    tokens_minute: int = betterproto.int64_field(7)


@dataclass(eq=False, repr=False)
class RateUsage(betterproto.Message):
    company_id: int = betterproto.int64_field(1)
    requests_day: int = betterproto.int64_field(2)
    requests_minute: int = betterproto.int64_field(3)
    tokens_day: int = betterproto.int64_field(4)
    tokens_minute: int = betterproto.int64_field(5)


@dataclass(eq=False, repr=False)
class RequestInfo(betterproto.Message):
    request_id: str = betterproto.string_field(1)
    company_id: int = betterproto.int64_field(2)
    application_id: int = betterproto.int64_field(3)
    application_action_id: int = betterproto.int64_field(4)
    model: str = betterproto.string_field(5)
    date_created: int = betterproto.int64_field(6)
    prompt_tokens: int = betterproto.int64_field(7)
