# Generated by Django 5.1.4 on 2024-12-26 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hashes',
            fields=[
                ('table_name', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('md5_hash', models.CharField(max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
